FROM python:3.10 AS django-static-builder

ARG EXAM_DATABASE_SQLITE=/tmp/tmp-sqlite.db

## Install poetry
RUN pip install --no-cache-dir poetry==1.1.13

COPY . /app/src

WORKDIR /app/src/exam

## Install app requirements
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

RUN ./manage.py collectstatic --noinput

## Final stage
FROM nginx:1.20

COPY --from=django-static-builder /app/src/exam/static /data/static

WORKDIR /data
